import Emittery from 'emittery'

export const EventEmitter = new Emittery()

export const EVENT_NAMES = {
  SEND_LINE_INDEX: 'SEND_LINE_INDEX',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  HANDLE_SELECTION_MENU: 'HANDLE_SELECTION_MENU',
  HANDLE_DICT_QUERY: 'HANDLE_DICT_QUERY',
  SEND_SELECTED_SENTENCE: 'SEND_SELECTED_SENTENCE',
}

